CREATE TABLE [dbo].[Student]
(
	[StudentId] VARCHAR(100) NOT NULL PRIMARY KEY,
	[FirstName] VARCHAR(100) NOT NULL,
	[LastName] VARCHAR(100) NOT NULL,
	[Email] VARCHAR(100) NOT NULL,
	[Mobile] VARCHAR(100) NOT NULL
)
